# Generated by Django 4.2 on 2025-03-17 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0004_remove_order_status_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 11, 19, 34, 438296, tzinfo=datetime.timezone.utc)),
        ),
    ]
