# Generated by Django 4.2 on 2025-03-19 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0008_reward_rename_timestamp_notification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 19, 11, 7, 46, 565586, tzinfo=datetime.timezone.utc)),
        ),
    ]
