# Generated by Django 4.2 on 2025-03-19 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0011_alter_passwordreset_expires_at_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 19, 12, 35, 5, 510367, tzinfo=datetime.timezone.utc)),
        ),
    ]
