# Generated by Django 4.2 on 2025-03-21 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0012_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 14, 12, 40, 145481, tzinfo=datetime.timezone.utc)),
        ),
    ]
