# Generated by Django 4.2 on 2025-03-24 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0013_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 24, 11, 51, 44, 396504, tzinfo=datetime.timezone.utc)),
        ),
    ]
