# Generated by Django 4.2 on 2025-03-28 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0016_alter_passwordreset_expires_at_redeemedreward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 28, 15, 32, 8, 687778, tzinfo=datetime.timezone.utc)),
        ),
    ]
