# Generated by Django 4.2 on 2025-03-28 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0017_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 28, 20, 46, 33, 887307, tzinfo=datetime.timezone.utc)),
        ),
    ]
